-- CREATE TABLE films (id int, name varchar(255), description varchar(255), actors varchar(255));
-- INSERT INTO film (id, title, description, actors) VALUES (1, 'Titanic', 'film romantique', 'DiCaprio Leonardo');
-- INSERT INTO film (id, title, description, actors)  VALUES (2, 'Star Wars', 'Darth Vader is adamant', 'Star Wars');